=== faisalbrahvii/Xml/externaldtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT aptech (employe* , students*)>
<!ELEMENT employe (name , contact , email, salary)>
<!ELEMENT students (name , contact , email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== faisalbrahvii/Xml/external.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aptech SYSTEM "externaldtd.dtd" [


]>

<aptech>
    <employe>
        <name>Ali</name>
        <contact>0323213213</contact>
        <email>alui@gmail.com </email>
        <salary>60000</salary>
    </employe>
    <employe>
        <name>rafay</name>
        <contact>03142343</contact>
        <email>rafay@gmail.com </email>
        <salary>64000</salary>
    </employe>
    <students>
        <name>Hamza</name>
        <contact>0892374</contact>
        <email>ham@gmail.com</email>

    </students>
</aptech>
